networks:
  my-network:
    external: true

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=picpaysimplified
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - '5433:5432'
    networks:
      - my-network
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - my-network
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
        - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/picpaysimplified
        - SPRING_DATASOURCE_USERNAME=myuser
        - SPRING_DATASOURCE_PASSWORD=secret
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
      - kafka
    networks:
      - my-network
