spring.application.name=picpaysimplified
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:postgresql://localhost:5432/picpaysimplified
#spring.datasource.username=postgres
#spring.datasource.password=123456
#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

api.secret.key=135988319538195sfdgbfshgb381954r83195

api.authorization.url=https://util.devi.tools/api/v2/authorize